version: "3.9"

services:
  nginx:
    container_name: p-bri-web-${STAGE}
    image: p-bri-web-${STAGE}
    # restart: always
    build:
      context: .
      dockerfile: nginx.Dockerfile
      args:
        STAGE: ${STAGE}
    ports:
      - "${WEB_PORT}:${WEB_PORT}"
    # volumes:
    #   - ./nginx.conf:/etc/nginx/nginx.conf:ro
    # depends_on:
    #   app:
    #     condition: service_completed_successfully
  # app:
  #   container_name: app-bri-${STAGE}
  #   image: app-bri-${STAGE}
  #   build:
  #     context: .
  #     dockerfile: web.Dockerfile
  #     args:
  #       STAGE: ${STAGE}
  # restart: always
