const plugin = require("tailwindcss/plugin");

module.exports = {
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  plugins: [
    plugin(({ addUtilities }) => {
      const newUtilities = {
        ".sm_heading_h1": {
          fontFamily: "var(--sm-main-font-family)",
          fontSize: "72px",
          fontWeight: "600",
          lineHeight: "80px",
          letterSpacing: "0px",
          textAlign: "left",
        },
        ".sm_heading_h2": {
          fontFamily: "var(--sm-main-font-family)",
          fontSize: "64px",
          fontWeight: "600",
          lineHeight: "72px",
          letterSpacing: "0px",
          textAlign: "left",
        },
        ".sm_heading_h3": {
          fontFamily: "var(--sm-main-font-family)",
          fontSize: "48px",
          fontWeight: "600",
          lineHeight: "56px",
          letterSpacing: "0px",
          textAlign: "left",
        },
        ".sm_heading_h4": {
          fontFamily: "var(--sm-main-font-family)",
          fontSize: "36px",
          fontWeight: "600",
          lineHeight: "48px",
          letterSpacing: "0px",
          textAlign: "left",
        },
        ".sm_heading_h5": {
          fontFamily: "var(--sm-main-font-family)",
          fontSize: "24px",
          fontWeight: "600",
          lineHeight: "32px",
          letterSpacing: "0px",
          textAlign: "left",
        },
        ".sm_title_t1_caps": {
          fontFamily: "var(--sm-main-font-family)",
          fontSize: "20px",
          fontWeight: "700",
          lineHeight: "28px",
          letterSpacing: "0em",
          textAlign: "left",
        },
        ".sm_title_t1_semi": {
          fontFamily: "var(--sm-main-font-family)",
          fontSize: "20px",
          fontWeight: "600",
          lineHeight: "28px",
          letterSpacing: "0em",
          textAlign: "left",
        },
        ".sm_sub_title_semi": {
          fontFamily: "var(--sm-main-font-family)",
          fontSize: "18px",
          fontWeight: "600",
          lineHeight: "24px",
          letterSpacing: "0px",
          textAlign: "left",
        },
        ".sm_sub_title_reg": {
          fontFamily: "var(--sm-main-font-family)",
          fontSize: "18px",
          fontWeight: "400",
          lineHeight: "24px",
          letterSpacing: "0px",
          textAlign: "left",
        },
        ".sm_body_b1_semi": {
          fontFamily: "var(--sm-main-font-family)",
          fontSize: "16px",
          fontWeight: "600",
          lineHeight: "24px",
          letterSpacing: "0px",
          textAlign: "left",
        },
        ".sm_body_b1_reg": {
          fontFamily: "var(--sm-main-font-family)",
          fontSize: "16px",
          fontWeight: "400",
          lineHeight: "24px",
          letterSpacing: "0px",
          textAlign: "left",
        },
        ".sm_body_b2_semi": {
          fontFamily: "var(--sm-main-font-family)",
          fontSize: "14px",
          fontWeight: "600",
          lineHeight: "20px",
          letterSpacing: "0em",
          textAlign: "left",
        },
        ".sm_body_b2_reg": {
          fontFamily: "var(--sm-main-font-family)",
          fontSize: "14px",
          fontWeight: "400",
          lineHeight: "20px",
          letterSpacing: "0em",
          textAlign: "left",
        },
        ".sm_body_b2_reg_center": {
          fontFamily: "var(--sm-main-font-family)",
          fontSize: "14px",
          fontWeight: "400",
          lineHeight: "20px",
          letterSpacing: "0em",
          textAlign: "center",
        },
        ".sm_body_b3_semi": {
          fontFamily: "var(--sm-main-font-family)",
          fontSize: "12px",
          fontWeight: "600",
          lineHeight: "16px",
          letterSpacing: "0em",
          textAlign: "left",
        },
        ".sm_body_b3_reg": {
          fontFamily: "var(--sm-main-font-family)",
          fontSize: "12px",
          fontWeight: "400",
          lineHeight: "16px",
          letterSpacing: "0em",
          textAlign: "left",
        },
        ".sm_body_all_caps_bold": {
          fontFamily: "var(--sm-main-font-family)",
          fontSize: "12px",
          fontWeight: "700",
          lineHeight: "16px",
          letterSpacing: "0.4px",
          textAlign: "left",
        },
        ".sm_body_all_reg": {
          fontFamily: "var(--sm-main-font-family)",
          fontSize: "12px",
          fontWeight: "400",
          lineHeight: "16px",
          letterSpacing: "0.4px",
          textAlign: "left",
        },
        ".shadow-custom": {
          boxShadow: "inset 0px 1px 0px var(--gray-200)",
        },
        ".word-overflow-break": {
          wordBreak: "break-word",
          overflowWrap: "break-word",
        },
      };
      addUtilities(newUtilities);
    }),
  ],
  corePlugins: {
    preflight: false,
  },
  theme: {
    colors: ({ colors }) => ({
      ...colors,
      blue800: "var(--blue-800)",
      blue700: "var(--blue-700)",
      blue600: "var(--blue-600)",
      blue500: "var(--blue-500)",
      blue400: "var(--blue-400)",
      blue300: "var(--blue-300)",
      blue200: "var(--blue-200)",
      blue100: "var(--blue-100)",
      blue50: "var(--blue-50)",

      lightBlue700: "var(--light-blue-700)",
      lightBlue600: "var(--light-blue-600)",
      lightBlue500: "var(--light-blue-500)",
      lightBlue400: "var(--light-blue-400)",
      lightBlue300: "var(--light-blue-300)",
      lightBlue200: "var(--light-blue-200)",
      lightBlue100: "var(--light-blue-100)",
      lightBlue50: "var(--light-blue-50)",

      yellow700: "var(--yellow-700)",
      yellow600: "var(--yellow-600)",
      yellow500: "var(--yellow-500)",
      yellow400: "var(--yellow-400)",
      yellow300: "var(--yellow-300)",
      yellow200: "var(--yellow-200)",
      yellow100: "var(--yellow-100)",
      yellow50: "var(--yellow-50)",

      orange700: "var(--orange-700)",
      orange600: "var(--orange-600)",
      orange500: "var(--orange-500)",
      orange400: "var(--orange-400)",
      orange300: "var(--orange-300)",
      orange200: "var(--orange-200)",
      orange100: "var(--orange-100)",
      orange50: "var(--orange-50)",

      red700: "var(--red-700)",
      red600: "var(--red-600)",
      red500: "var(--red-500)",
      red400: "var(--red-400)",
      red300: "var(--red-300)",
      red200: "var(--red-200)",
      red100: "var(--red-100)",
      red50: "var(--red-50)",

      pink700: "var(--pink-700)",
      pink600: "var(--pink-600)",
      pink500: "var(--pink-500)",
      pink400: "var(--pink-400)",
      pink300: "var(--pink-300)",
      pink200: "var(--pink-200)",
      pink100: "var(--pink-100)",
      pink50: "var(--pink-50)",

      purple700: "var(--purple-700)",
      purple600: "var(--purple-600)",
      purple500: "var(--purple-500)",
      purple400: "var(--purple-400)",
      purple300: "var(--purple-300)",
      purple200: "var(--purple-200)",
      purple100: "var(--purple-100)",
      purple50: "var(--purple-50)",

      gray800: "var(--gray-800)",
      gray600: "var(--gray-600)",
      gray500: "var(--gray-500)",
      gray400: "var(--gray-400)",
      gray300: "var(--gray-300)",
      gray200: "var(--gray-200)",
      gray100: "var(--gray-100)",
      gray50: "var(--gray-50)",

      green700: "var(--green-700)",
      green600: "var(--green-600)",
      green500: "var(--green-500)",
      green400: "var(--green-400)",
      green300: "var(--green-300)",
      green200: "var(--green-200)",
      green100: "var(--green-100)",
      green50: "var(--green-50)",
    }),
    extend: {
      boxShadow: {
        common:
          "0px 2px 4px rgba(40, 41, 61, 0.04), 0px 4px 16px rgba(96, 97, 112, 0.16)",
        "elevation-01":
          "0px 0px 1px rgba(40, 41, 61, 0.08), 0px 0.5px 2px rgba(96, 97, 112, 0.16)",
        "elevation-02":
          "0px 0px 1px rgba(40, 41, 61, 0.04), 0px 2px 4px 2px rgba(96, 97, 112, 0.07)",
        "elevation-03":
          "0px 0px 2px rgba(40, 41, 61, 0.04), 0px 2px 8px rgba(96, 97, 112, 0.16)",
        "elevation-04":
          "0px 2px 4px rgba(40, 41, 61, 0.04), 0px 4px 16px rgba(96, 97, 112, 0.16)",
        "elevation-05":
          "0px 2px 8px rgba(40, 41, 61, 0.04), 0px 6px 24px rgba(96, 97, 112, 0.16)",
        "elevation-06":
          "0px 2px 8px rgba(40, 41, 61, 0.08), 0px 12px 32px rgba(96, 97, 112, 0.24)",
      },
      colors: {
        primaryColor: "#6085ff",
      },
      gridTemplateColumns: {
        "auto-fill": "repeat(auto-fill, minmax(276px, 1fr))",
      },
    },
  },
};
